/**
 * Exporters - Fungsi untuk export data ke berbagai format
 */

/**
 * Convert array of objects ke CSV
 */
export function exportCSV(data: Record<string, any>[], filename: string): void {
  if (!data || data.length === 0) {
    alert('Tidak ada data untuk diexport');
    return;
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row =>
      headers
        .map(h => {
          const val = row[h];
          if (val === null || val === undefined) return '';
          const str = String(val).replace(/"/g, '""');
          if (str.includes(',') || str.includes('\n') || str.includes('"')) {
            return `"${str}"`;
          }
          return str;
        })
        .join(',')
    ),
  ].join('\n');

  downloadFile(csvContent, `${filename}.csv`, 'text/csv');
}

/**
 * Export ke format XLS (HTML table yang bisa dibuka Excel)
 */
export function exportXLS(data: Record<string, any>[], filename: string): void {
  if (!data || data.length === 0) {
    alert('Tidak ada data untuk diexport');
    return;
  }

  const headers = Object.keys(data[0]);
  let html = '<table border="1"><thead><tr>';
  headers.forEach(h => {
    html += `<th>${h}</th>`;
  });
  html += '</tr></thead><tbody>';

  data.forEach(row => {
    html += '<tr>';
    headers.forEach(h => {
      const val = row[h];
      html += `<td>${val !== null && val !== undefined ? val : ''}</td>`;
    });
    html += '</tr>';
  });

  html += '</tbody></table>';

  downloadFile(html, `${filename}.xls`, 'application/vnd.ms-excel');
}

/**
 * Export ke format TXT
 */
export function exportTXT(data: Record<string, any>[], filename: string): void {
  if (!data || data.length === 0) {
    alert('Tidak ada data untuk diexport');
    return;
  }

  const headers = Object.keys(data[0]);
  let text = headers.join('\t') + '\n';

  data.forEach(row => {
    text += headers.map(h => row[h] ?? '').join('\t') + '\n';
  });

  downloadFile(text, `${filename}.txt`, 'text/plain');
}

/**
 * Export ke format PDF menggunakan window.print
 */
export function exportPDF(data: Record<string, any>[], title: string): void {
  if (!data || data.length === 0) {
    alert('Tidak ada data untuk diexport');
    return;
  }

  const headers = Object.keys(data[0]);
  let html = `
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { text-align: center; color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <p>Tanggal: ${new Date().toLocaleDateString('id-ID')}</p>
      <table>
        <thead>
          <tr>
            ${headers.map(h => `<th>${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${data
            .map(
              row =>
                `<tr>${headers.map(h => `<td>${row[h] ?? ''}</td>`).join('')}</tr>`
            )
            .join('')}
        </tbody>
      </table>
      <div class="footer">
        Generated by Church Management System
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  }
}

/**
 * Export ke format DOCX (HTML yang bisa dibuka Word)
 */
export function exportDOCX(data: Record<string, any>[], title: string): void {
  if (!data || data.length === 0) {
    alert('Tidak ada data untuk diexport');
    return;
  }

  const headers = Object.keys(data[0]);
  let html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #000; padding: 8px; }
        th { background-color: #f2f2f2; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <table>
        <thead>
          <tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${data
            .map(
              row =>
                `<tr>${headers.map(h => `<td>${row[h] ?? ''}</td>`).join('')}</tr>`
            )
            .join('')}
        </tbody>
      </table>
    </body>
    </html>
  `;

  downloadFile(html, `${title}.doc`, 'application/msword');
}

/**
 * Helper: Download file dari string content
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType + ';charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Backup seluruh data ke JSON file
 */
export function backupData(data: Record<string, any>): void {
  const jsonStr = JSON.stringify(data, null, 2);
  const filename = `cms-backup-${new Date().toISOString().split('T')[0]}.json`;
  downloadFile(jsonStr, filename, 'application/json');
}

/**
 * Restore data dari JSON file
 */
export function restoreData(file: File): Promise<Record<string, any>> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = e => {
      try {
        const data = JSON.parse(e.target?.result as string);
        resolve(data);
      } catch {
        reject(new Error('File JSON tidak valid'));
      }
    };
    reader.onerror = () => reject(new Error('Gagal membaca file'));
    reader.readAsText(file);
  });
}
